# Generated by Django 3.2.7 on 2021-09-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Заголовок')),
                ('price', models.DecimalField(decimal_places=4, max_digits=10000000, verbose_name='Цена')),
                ('url', models.URLField(verbose_name='ссылка')),
            ],
        ),
    ]
